dist: trusty
language: java
jdk:
- openjdk11

addons:
  sonarcloud:
    organization: gulixciurli
    token: a3ab5602f53519757eb80edcc9d2e10ef935a214

     
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=myorg_myrepo

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn compile sonar:sonar  -Dsonar.projectKey=gulixciurli_bookkeeper -Ppit  -Dmaven.javadoc.skip=true

  # - mvn clean -DskipTests
